AWSTemplateFormatVersion: "2010-09-09"
Description: T3-Wagu Production RDS MySQL Stack

Parameters:
  DBName:
    Type: String
    Default: wagudb

  DBInstanceClass:
    Type: String
    Default: db.m5.large # 운영 기준

  AllocatedStorage:
    Type: Number
    Default: 50

  MasterUsername:
    Type: String
    Default: wagu_admin
    AllowedPattern: "[a-zA-Z0-9_]+"

  MasterPassword:
    Type: String
    NoEcho: true
    MinLength: 12

Resources:
  WaguProdDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL from App VPC
      VpcId: !ImportValue T3-Wagu-Matching-VPC-Id

  WaguProdDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Prod subnet group for Wagu RDS
      SubnetIds: !Split
        - ","
        - !ImportValue T3-Wagu-Matching-Private-Db-Subnet-Ids

  WaguProdDBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot # 삭제 시 스냅샷 남김
    UpdateReplacePolicy: Snapshot # 교체 시 스냅샷
    Properties:
      DBInstanceIdentifier: t3-wagu-prod-db
      Engine: mysql
      EngineVersion: "8.0.34"
      DBName: !Ref DBName

      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref AllocatedStorage
      StorageType: gp2
      StorageEncrypted: true

      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterPassword

      PubliclyAccessible: false # 내부 접근만
      MultiAZ: true # 고가용성
      BackupRetentionPeriod: 14 # 운영 백업
      PreferredBackupWindow: 02:00-03:00

      VPCSecurityGroups:
        - !Ref WaguProdDBSecurityGroup
      DBSubnetGroupName: !Ref WaguProdDBSubnetGroup

      DeletionProtection: true
      EnableCloudwatchLogsExports:
        - error
        - general
        - slowquery

Outputs:
  ProdDBEndpoint:
    Description: Production RDS Endpoint
    Value: !GetAtt WaguProdDBInstance.Endpoint.Address

  ProdDBPort:
    Description: Production RDS Port
    Value: !GetAtt WaguProdDBInstance.Endpoint.Port
