AWSTemplateFormatVersion: "2010-09-09"
Description: "WaguWagu Project: S3 Bucket Setup"

Resources:
  WaguWaguBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "waguwagu-s3-bucket-${AWS::AccountId}-${AWS::Region}"
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Name
          Value: waguwagu-s3-bucket

Outputs:
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref WaguWaguBucket
    Export:
      Name: waguwagu-s3-bucket

  BucketArn:
    Description: S3 Bucket ARN
    Value: !GetAtt WaguWaguBucket.Arn
    Export:
      Name: waguwagu-s3-bucket-arn
