AWSTemplateFormatVersion: '2010-09-09'
Description: T3-Wagu RDS MySQL Database Stack

Parameters:
  DBName:
    Type: String
    Default: wagudb
  DBInstanceClass:
    Type: String
    Default: db.t3.micro
  AllocatedStorage:
    Type: Number
    Default: 20
  
   # 마스터 계정 정보
  MasterUsername:
    Type: String
    Description: Enter the master username for the DB
    Default: t3_admin
    AllowedPattern: '[a-zA-Z0-9_]+'

  MasterPassword:
    Type: String
    Description: Enter the master password for the DB (Min 8 chars)
    NoEcho: true
    MinLength: 8

Resources:
  WaguDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL access
      VpcId: !ImportValue T3-Wagu-Game-VPC-Id


  WaguDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Wagu RDS
      SubnetIds: !Split
        - ","
        - !ImportValue T3-Wagu-Game-Private-Db-Subnet-Ids

  WaguDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: t3-wagu-db
      Engine: mysql
      EngineVersion: "8.0"
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref AllocatedStorage
      StorageType: gp2
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterPassword
      PubliclyAccessible: false
      MultiAZ: true
      BackupRetentionPeriod: 7
      VPCSecurityGroups:
        - !Ref WaguDBSecurityGroup
      DBSubnetGroupName: !Ref WaguDBSubnetGroup
      DeletionProtection: false

Outputs:
  DBEndpoint:
    Description: RDS Endpoint
    Value: !GetAtt WaguDBInstance.Endpoint.Address
  DBPort:
    Description: RDS Port
    Value: !GetAtt WaguDBInstance.Endpoint.Port
