AWSTemplateFormatVersion: "2010-09-09"
Description: Jenkins Server for WAGUWAGU

Parameters:
  ProjectPrefix:
    Type: String
    Default: T3-Wagu
  
  InstanceType:
    Type: String
    Default: t3.medium
    AllowedValues:
      - t3.medium
      - t3.large
      - t3.xlarge
  
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64'
    Description: Latest Amazon Linux 2023 AMI ID from SSM Parameter Store
  

  JenkinsAdminUser:
    Type: String
    Default: admin

  JenkinsAdminPassword:
    Type: String
    NoEcho: true

  JenkinsBaseUrl:
    Type: String
    Default: ""   # 예: http://your-domain-or-ip:8080 (없으면 빈 값)


Resources:
  ############################################################
  # IAM Role for Jenkins
  ############################################################
  JenkinsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectPrefix}-Jenkins-Role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      Policies:
        - PolicyName: JenkinsECRPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:GetRepositoryPolicy
                  - ecr:DescribeRepositories
                  - ecr:ListImages
                  - ecr:DescribeImages
                  - ecr:BatchGetImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
                Resource: "*"

  JenkinsInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref JenkinsRole
      InstanceProfileName: !Sub "${ProjectPrefix}-Jenkins-Instance-Profile"


  ############################################################
  # Jenkins EC2 Instance (Matching)
  ############################################################
  JenkinsInstanceMatching:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      IamInstanceProfile: !Ref JenkinsInstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - !ImportValue T3-Wagu-JenkinsMatchingSGId
          # 첫번째 서브넷 사용
          SubnetId: !Select [0, !Split [",", !ImportValue T3-Wagu-Matching-Public-Subnet-Ids]]
      
       # Jenkins 자동 설치(UserData)
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -euxo pipefail

          # 로그 남기기 (실패 원인 숨기지 않기)
          exec > >(tee /var/log/user-data.log | logger -t user-data -s 2>/dev/console) 2>&1

          dnf update -y
          dnf install -y java-17-amazon-corretto

          # Jenkins repo (공식 문서 방식)
          wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
          rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

          dnf clean all
          dnf makecache -y

          dnf install -y jenkins

          # Setup wizard 스킵 (기존 옵션 덮어쓰기 말고 append)
          mkdir -p /etc/sysconfig
          if [ -f /etc/sysconfig/jenkins ] && grep -q '^JENKINS_JAVA_OPTIONS=' /etc/sysconfig/jenkins; then
            sed -i 's#^JENKINS_JAVA_OPTIONS="\(.*\)"#JENKINS_JAVA_OPTIONS="\1 -Djenkins.install.runSetupWizard=false"#' /etc/sysconfig/jenkins
          else
            echo 'JENKINS_JAVA_OPTIONS="-Djenkins.install.runSetupWizard=false"' >> /etc/sysconfig/jenkins
          fi

          systemctl daemon-reload
          systemctl enable jenkins
          systemctl stop jenkins || true

          # 관리자 계정 자동 생성
          mkdir -p /var/lib/jenkins/init.groovy.d
          cat >/var/lib/jenkins/init.groovy.d/01-security.groovy <<'GROOVY'
          import jenkins.model.*
          import hudson.security.*
          import jenkins.model.JenkinsLocationConfiguration

          def instance = Jenkins.get()

          def adminUser = "${JenkinsAdminUser}"
          def adminPass = "${JenkinsAdminPassword}"

          def realm = new HudsonPrivateSecurityRealm(false)
          if (realm.getUser(adminUser) == null) {
            realm.createAccount(adminUser, adminPass)
          }
          instance.setSecurityRealm(realm)

          def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
          strategy.setAllowAnonymousRead(false)
          instance.setAuthorizationStrategy(strategy)

          def baseUrl = "${JenkinsBaseUrl}"
          if (baseUrl != null && baseUrl.trim().length() > 0) {
            def loc = JenkinsLocationConfiguration.get()
            loc.setUrl(baseUrl.trim())
            loc.save()
          }

          instance.save()
          GROOVY

          chown -R jenkins:jenkins /var/lib/jenkins/init.groovy.d

          systemctl start jenkins
          systemctl status jenkins --no-pager || true
          ss -lntp | grep 8080 || true
          curl -fsSLI http://localhost:8080/login || true

      
      Tags:
        - Key: Name
          Value: !Sub "${ProjectPrefix}-Jenkins-Matching"
        - Key: Project
          Value: WAGUWAGU

  ############################################################
  # Jenkins EC2 Instance (Game)
  ############################################################
  JenkinsInstanceGame:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      IamInstanceProfile: !Ref JenkinsInstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - !ImportValue T3-Wagu-JenkinsGameSGId
          # 첫번째 서브넷 사용
          SubnetId: !Select [0, !Split [",", !ImportValue T3-Wagu-Game-Public-Subnet-Ids]]
      
       # Jenkins 자동 설치(UserData) 혹시 몰라서 남겨둡니다 ㅎ..
      # UserData:
      #   Fn::Base64: !Sub |
      #     #!/bin/bash
      #     set -euxo pipefail

      #     dnf update -y

      #     # Java 17 (Jenkins 실행 필수)
      #     dnf install -y java-17-amazon-corretto

      #     # Jenkins repo 추가
      #     curl -fsSL https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key | tee /etc/pki/rpm-gpg/RPM-GPG-KEY-jenkins > /dev/null
      #     cat >/etc/yum.repos.d/jenkins.repo <<'EOF'
      #     [jenkins]
      #     name=Jenkins-stable
      #     baseurl=https://pkg.jenkins.io/redhat-stable
      #     gpgcheck=1
      #     gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-jenkins
      #     EOF

      #     dnf install -y jenkins

      #     systemctl enable jenkins
      #     systemctl start jenkins

      #     # 설치 확인용 로그
      #     systemctl status jenkins --no-pager || true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -euxo pipefail

          # 로그 남기기 (실패 원인 숨기지 않기)
          exec > >(tee /var/log/user-data.log | logger -t user-data -s 2>/dev/console) 2>&1

          dnf update -y
          dnf install -y java-17-amazon-corretto

          # Jenkins repo (공식 문서 방식)
          wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
          rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

          dnf clean all
          dnf makecache -y

          dnf install -y jenkins

          # Setup wizard 스킵 (기존 옵션 덮어쓰기 말고 append)
          mkdir -p /etc/sysconfig
          if [ -f /etc/sysconfig/jenkins ] && grep -q '^JENKINS_JAVA_OPTIONS=' /etc/sysconfig/jenkins; then
            sed -i 's#^JENKINS_JAVA_OPTIONS="\(.*\)"#JENKINS_JAVA_OPTIONS="\1 -Djenkins.install.runSetupWizard=false"#' /etc/sysconfig/jenkins
          else
            echo 'JENKINS_JAVA_OPTIONS="-Djenkins.install.runSetupWizard=false"' >> /etc/sysconfig/jenkins
          fi

          systemctl daemon-reload
          systemctl enable jenkins
          systemctl stop jenkins || true

          # 관리자 계정 자동 생성
          mkdir -p /var/lib/jenkins/init.groovy.d
          cat >/var/lib/jenkins/init.groovy.d/01-security.groovy <<'GROOVY'
          import jenkins.model.*
          import hudson.security.*
          import jenkins.model.JenkinsLocationConfiguration

          def instance = Jenkins.get()

          def adminUser = "${JenkinsAdminUser}"
          def adminPass = "${JenkinsAdminPassword}"

          def realm = new HudsonPrivateSecurityRealm(false)
          if (realm.getUser(adminUser) == null) {
            realm.createAccount(adminUser, adminPass)
          }
          instance.setSecurityRealm(realm)

          def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
          strategy.setAllowAnonymousRead(false)
          instance.setAuthorizationStrategy(strategy)

          def baseUrl = "${JenkinsBaseUrl}"
          if (baseUrl != null && baseUrl.trim().length() > 0) {
            def loc = JenkinsLocationConfiguration.get()
            loc.setUrl(baseUrl.trim())
            loc.save()
          }

          instance.save()
          GROOVY

          chown -R jenkins:jenkins /var/lib/jenkins/init.groovy.d

          systemctl start jenkins
          systemctl status jenkins --no-pager || true
          ss -lntp | grep 8080 || true
          curl -fsSLI http://localhost:8080/login || true


      
      Tags:
        - Key: Name
          Value: !Sub "${ProjectPrefix}-Jenkins-Game"
        - Key: Project
          Value: WAGUWAGU

Outputs:
  JenkinsInstanceMatchingId:
    Value: !Ref JenkinsInstanceMatching
    Description: Instance ID of the Jenkins Matching Server
    Export:
      Name: !Sub "${ProjectPrefix}-Jenkins-Matching-Instance-Id"

  JenkinsInstanceMatchingPublicIp:
    Value: !GetAtt JenkinsInstanceMatching.PublicIp
    Description: Public IP of the Jenkins Matching Server

  JenkinsInstanceGameId:
    Value: !Ref JenkinsInstanceGame
    Description: Instance ID of the Jenkins Game Server
    Export:
      Name: !Sub "${ProjectPrefix}-Jenkins-Game-Instance-Id"

  JenkinsInstanceGamePublicIp:
    Value: !GetAtt JenkinsInstanceGame.PublicIp
    Description: Public IP of the Jenkins Game Server
